# Generated by Django 3.0.6 on 2020-05-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, blank=True, verbose_name='Created')),
                ('title', models.CharField(help_text='Short descriptive text', max_length=200, verbose_name='Title')),
                ('to_hide', models.CharField(blank=True, default='yes', help_text='Secret field', max_length=10, verbose_name='To hide')),
                ('dummy', models.CharField(blank=True, default='dummy', help_text='This is just a dummy', max_length=100, verbose_name='Dummy')),
                ('email', models.EmailField(help_text='Where to send a message', max_length=254, verbose_name='Email')),
                ('contents', models.TextField(verbose_name='Contents')),
                ('approved', models.BooleanField(default=False, help_text='Whether it was approved', verbose_name='Approved')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Article status', verbose_name='Status')),
                ('attach', models.FileField(help_text='Custom user attachment', upload_to='', verbose_name='Attachment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Author', verbose_name='Author')),
            ],
        ),
    ]
