# Generated by Django 3.0.6 on 2020-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='formsub1',
            field=models.CharField(blank=True, default='{"first": "f", "second": "s"}', help_text='This part is from subform', max_length=250, verbose_name='Subform'),
        ),
        migrations.AlterField(
            model_name='article',
            name='attach',
            field=models.FileField(blank=True, help_text='Custom user attachment', null=True, upload_to='', verbose_name='Attachment'),
        ),
    ]
